import { defineBlock } from "lineadraw";

const style1: Partial<Text> = {
  hAlign: "right",
  vAlign: "top",
  styleOverride: { widthFactor: 0.8, textHeight: 1.5 },
};

const style2: Partial<Text> = {
  hAlign: "right",
  vAlign: "top",
  styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
};

const style3: Partial<Text> = {
  hAlign: "right",
  vAlign: "top",
  styleOverride: { widthFactor: 0.8, textHeight: 2.5 },
};

const lang_labels = {
  en: {
    project_name: "PROJECT NAME",
    drawing_content: "DRAWING CONTENT",
    scales: "SCALES",
    drawer: "DRAWER",
    designer: "DESIGNER",
    checker: "CHECKER",
    date: "DATE",
    project_number: "PROJECT NUMBER",
    design_group: "DESIGN GROUP",
    drawing_number: "DWG. NO.",
    page: "PAGE",
    revision: "REVISION",
  },
  fi: {
    project_name: "KOHDE",
    drawing_content: "PIIRUSTUKSEN SISÄLTÖ",
    scales: "MITTAKAAVAT",
    drawer: "PIIRT.",
    designer: "SUUN.",
    checker: "TARK.",
    date: "PVM",
    project_number: "TYÖNUMERO",
    design_group: "S. ALA",
    drawing_number: "PIIR. NRO.",
    page: "SIVU",
    revision: "MUUTOS",
  },
};

export default defineBlock({
  id: "@lineadraw/title-designer",
  name: "Title designer",
  description:
    "Draws a sheet title block filled from text-field parameters: project, site, designer and drawing information.",
  version: "1.0.0",
  authors: ["Linea Team"],
  tags: ["sheet", "title-block", "annotation", "layout"],
  params: [
    {
      name: "lang",
      label: "Language",
      type: "enum",
      options: [
        { value: "en", label: "English" },
        { value: "fi", label: "Finnish" },
      ],
      default: "en",
    },
    {
      name: "project_name_1",
      label: "Name 1",
      type: "string",
      default: "",
    },
    {
      name: "project_name_2",
      label: "Name 2",
      type: "string",
      default: "",
    },
    {
      name: "project_name_3",
      label: "Name 3",
      type: "string",
      default: "",
    },
    {
      name: "project_name_4",
      label: "Name 4",
      type: "string",
      default: "",
    },
    {
      name: "drawing_content_1",
      label: "Content 1",
      type: "string",
      default: "",
    },
    {
      name: "drawing_content_2",
      label: "Content 2",
      type: "string",
      default: "",
    },
    {
      name: "drawing_content_3",
      label: "Content 3",
      type: "string",
      default: "",
    },
    {
      name: "drawing_content_4",
      label: "Content 4",
      type: "string",
      default: "",
    },
    {
      name: "drawing_content_5",
      label: "Content 5",
      type: "string",
      default: "",
    },
    {
      name: "scales_1",
      label: "Scales 1",
      type: "string",
      default: "",
    },
    {
      name: "scales_2",
      label: "Scales 2",
      type: "string",
      default: "",
    },
    {
      name: "drawer_name",
      label: "Drawer",
      type: "string",
      default: "",
    },
    {
      name: "designer_name",
      label: "Designer",
      type: "string",
      default: "",
    },
    {
      name: "checker_name",
      label: "Checker",
      type: "string",
      default: "",
    },
    {
      name: "date",
      label: "Date",
      type: "string",
      default: "",
    },
    {
      name: "project_number",
      label: "Project Num",
      type: "string",
      default: "",
    },
    {
      name: "design_group",
      label: "Design Group",
      type: "string",
      default: "STR",
    },
    {
      name: "drawing_number",
      label: "Dwg. Number",
      type: "string",
      default: "",
    },
    {
      name: "page",
      label: "Page",
      type: "string",
      default: "",
    },
    {
      name: "revision",
      label: "Revision",
      type: "string",
      default: "",
    },
  ],
  draw: ({ params }) => {
    const {
      lang,
      project_name_1,
      project_name_2,
      project_name_3,
      project_name_4,
      drawing_content_1,
      drawing_content_2,
      drawing_content_3,
      drawing_content_4,
      drawing_content_5,
      scales_1,
      scales_2,
      drawer_name,
      designer_name,
      checker_name,
      date,
      project_number,
      design_group,
      drawing_number,
      page,
      revision,
    } = params;
    const labels = lang_labels[lang] ?? lang_labels["en"];
    return [
      {
        type: "polyline",
        points: [
          [0, 0],
          [0, 59.5],
          [-184, 59.5],
          [-184, 0],
        ],
        closed: true,
      },
      { type: "line", a: [-94, 0], b: [-94, 59.5] },
      { type: "line", a: [-184, 17], b: [0, 17] },
      { type: "line", a: [-184, 25.5], b: [-94, 25.5] },
      { type: "line", a: [-184, 34], b: [-94, 34] },
      { type: "line", a: [-94, 8.5], b: [0, 8.5] },
      { type: "line", a: [-139, 17], b: [-139, 34] },
      { type: "line", a: [-37, 0], b: [-37, 17] },
      { type: "line", a: [-14, 0], b: [-14, 8.5] },
      {
        type: "text",
        position: [-183, 57],
        content: labels.project_name,
        ...style1,
      },
      {
        type: "text",
        position: [-183, 52],
        content: project_name_1,
        ...style2,
      },
      {
        type: "text",
        position: [-183, 46.5],
        content: project_name_2,
        ...style2,
      },
      {
        type: "text",
        position: [-183, 41],
        content: project_name_3,
        ...style2,
      },
      {
        type: "text",
        position: [-183, 35.5],
        content: project_name_4,
        ...style2,
      },
      {
        type: "text",
        position: [-93, 57],
        content: labels.drawing_content,
        ...style1,
      },
      {
        type: "text",
        position: [-93, 52],
        content: drawing_content_1,
        ...style2,
      },
      {
        type: "text",
        position: [-93, 46.5],
        content: drawing_content_2,
        ...style2,
      },
      {
        type: "text",
        position: [-93, 41],
        content: drawing_content_3,
        ...style2,
      },
      {
        type: "text",
        position: [-93, 35.5],
        content: drawing_content_4,
        ...style2,
      },
      {
        type: "text",
        position: [-93, 30],
        content: drawing_content_5,
        ...style2,
      },
      {
        type: "text",
        position: [-20, 57],
        content: labels.scales,
        ...style1,
      },
      {
        type: "text",
        position: [-20, 52],
        content: scales_1,
        ...style2,
      },
      {
        type: "text",
        position: [-20, 46.5],
        content: scales_2,
        ...style2,
      },
      {
        type: "text",
        position: [-183, 31.5],
        content: labels.drawer,
        ...style1,
      },
      {
        type: "text",
        position: [-183, 27],
        content: drawer_name,
        ...style3,
      },
      {
        type: "text",
        position: [-138, 31.5],
        content: labels.designer,
        ...style1,
      },
      {
        type: "text",
        position: [-138, 27],
        content: designer_name,
        ...style3,
      },
      {
        type: "text",
        position: [-183, 23],
        content: labels.checker,
        ...style1,
      },
      {
        type: "text",
        position: [-183, 18.5],
        content: checker_name,
        ...style3,
      },
      {
        type: "text",
        position: [-138, 23],
        content: labels.date,
        ...style1,
      },
      {
        type: "text",
        position: [-138, 18.5],
        content: date,
        ...style3,
      },
      {
        type: "text",
        position: [-93, 14.5],
        content: labels.project_number,
        ...style1,
      },
      {
        type: "text",
        position: [-93, 10],
        content: project_number,
        ...style2,
      },
      {
        type: "text",
        position: [-36, 14.5],
        content: labels.design_group,
        ...style1,
      },
      {
        type: "text",
        position: [-36, 10],
        content: design_group,
        ...style2,
      },
      {
        type: "text",
        position: [-93, 6],
        content: labels.drawing_number,
        ...style1,
      },
      {
        type: "text",
        position: [-93, 1.5],
        content: drawing_number,
        ...style2,
      },
      {
        type: "text",
        position: [-36, 6],
        content: labels.page,
        ...style1,
      },
      {
        type: "text",
        position: [-36, 1.5],
        content: page,
        ...style2,
      },
      {
        type: "text",
        position: [-13, 6],
        content: labels.revision,
        ...style1,
      },
      {
        type: "text",
        position: [-13, 1.5],
        content: revision,
        ...style2,
      },
    ];
  },
});
