import { defineBlock } from "lineadraw";

export default defineBlock({
  id: "75b3f820-8781-4675-889d-8f1d4a46fcec",
  name: "Title",
  params: [
    {
      name: "dist_vill",
      label: "District/Village",
      type: "string",
      default: "",
    },
    {
      name: "block_estate",
      label: "Block/Estate",
      type: "string",
      default: "",
    },
    {
      name: "building_lot",
      label: "Building Lot",
      type: "string",
      default: "",
    },
    {
      name: "auth_notes",
      label: "Auth Notes",
      type: "string",
      default: "",
    },
    {
      name: "building_action",
      label: "Build Action",
      type: "string",
      default: "NEW BUILDING",
    },
    {
      name: "drawing_category",
      label: "Drawing cat.",
      type: "string",
      default: "STRUCTURAL DRAWING",
    },
    {
      name: "archiving_code",
      label: "Code",
      type: "string",
      default: "",
    },
    {
      name: "project_name_1",
      label: "Name 1",
      type: "string",
      default: "",
    },
    {
      name: "project_name_2",
      label: "Name 2",
      type: "string",
      default: "",
    },
    {
      name: "project_name_3",
      label: "Name 3",
      type: "string",
      default: "",
    },
    {
      name: "project_name_4",
      label: "Name 4",
      type: "string",
      default: "",
    },
    {
      name: "drawing_content_1",
      label: "Content 1",
      type: "string",
      default: "",
    },
    {
      name: "drawing_content_2",
      label: "Content 2",
      type: "string",
      default: "",
    },
    {
      name: "drawing_content_3",
      label: "Content 3",
      type: "string",
      default: "",
    },
    {
      name: "scales_1",
      label: "Scales 1",
      type: "string",
      default: "",
    },
    {
      name: "scales_2",
      label: "Scales 2",
      type: "string",
      default: "",
    },
    {
      name: "drawer_name",
      label: "Drawer",
      type: "string",
      default: "",
    },
    {
      name: "designer_name",
      label: "Designer",
      type: "string",
      default: "",
    },
    {
      name: "checker_name",
      label: "Checker",
      type: "string",
      default: "",
    },
    {
      name: "date",
      label: "Date",
      type: "string",
      default: "",
    },
    {
      name: "project_number",
      label: "Project Num",
      type: "string",
      default: "",
    },
    {
      name: "design_group",
      label: "Design Group",
      type: "string",
      default: "STR",
    },
    {
      name: "drawing_number",
      label: "Dwg. Number",
      type: "string",
      default: "",
    },
    {
      name: "page",
      label: "Page",
      type: "string",
      default: "",
    },
    {
      name: "revision",
      label: "Revision",
      type: "string",
      default: "",
    },
  ],
  draw: ({ params }) => {
    const {
      dist_vill,
      block_estate,
      building_lot,
      auth_notes,
      building_action,
      drawing_category,
      archiving_code,
      project_name_1,
      project_name_2,
      project_name_3,
      project_name_4,
      drawing_content_1,
      drawing_content_2,
      drawing_content_3,
      scales_1,
      scales_2,
      drawer_name,
      designer_name,
      checker_name,
      date,
      project_number,
      design_group,
      drawing_number,
      page,
      revision,
    } = params;
    return [
      {
        type: "line",
        a: { x: 0, y: 59.5 },
        b: { x: 184, y: 59.5 },
      },
      {
        type: "line",
        a: { x: 0, y: 0 },
        b: { x: 184, y: 0 },
      },
      {
        type: "line",
        a: { x: 45, y: 17 },
        b: { x: 45, y: 34 },
      },
      {
        type: "line",
        a: { x: 0, y: 17 },
        b: { x: 184, y: 17 },
      },
      {
        type: "line",
        a: { x: 0, y: 34 },
        b: { x: 90, y: 34 },
      },
      {
        type: "line",
        a: { x: 0, y: 76.5 },
        b: { x: 0, y: 0 },
      },
      {
        type: "line",
        a: { x: 90, y: 25.5 },
        b: { x: 0, y: 25.5 },
      },
      {
        type: "line",
        a: { x: 90, y: 0 },
        b: { x: 90, y: 76.5 },
      },
      {
        type: "line",
        a: { x: 90, y: 8.5 },
        b: { x: 184, y: 8.5 },
      },
      {
        type: "line",
        a: { x: 147, y: 0 },
        b: { x: 147, y: 17 },
      },
      {
        type: "line",
        a: { x: 184, y: 76.5 },
        b: { x: 184, y: 0 },
      },
      {
        type: "line",
        a: { x: 170, y: 8.5 },
        b: { x: 170, y: 0 },
      },
      {
        type: "line",
        a: { x: 0, y: 76.5 },
        b: { x: 184, y: 76.5 },
      },
      {
        type: "line",
        a: { x: 0, y: 68 },
        b: { x: 184, y: 68 },
      },
      {
        type: "line",
        a: { x: 163, y: 68 },
        b: { x: 163, y: 59.5 },
      },

      {
        type: "text",
        position: { x: 1, y: 74 },
        content: "DISTRICT/VILLAGE",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 1.144531, y: 69 },
        content: dist_vill,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 31, y: 74 },
        content: "BLOCK/ESTATE",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 31, y: 69 },
        content: block_estate,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 61, y: 74 },
        content: "BUILDING LOT",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 61, y: 69 },
        content: building_lot,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 91, y: 74 },
        content: "AUTHORIZATION NOTES",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 91, y: 69 },
        content: auth_notes,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 1, y: 65.5 },
        content: "BUILDING ACTION",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 1, y: 60.5 },
        content: building_action,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 91, y: 65.5 },
        content: "DRAWING CATEGORY",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 91, y: 60.5 },
        content: drawing_category,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 164, y: 65.5 },
        content: "ARCHIVING CODE",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 164, y: 60.5 },
        content: archiving_code,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 1, y: 57 },
        content: "PROJECT NAME",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 1, y: 52 },
        content: project_name_1,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 1, y: 46.5 },
        content: project_name_2,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 1, y: 41 },
        content: project_name_3,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 1, y: 35.5 },
        content: project_name_4,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 91, y: 57 },
        content: "DRAWING CONTENT",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 91, y: 52 },
        content: drawing_content_1,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 91, y: 46.5 },
        content: drawing_content_2,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 91, y: 41 },
        content: drawing_content_3,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 164, y: 57 },
        content: "SCALES",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 164, y: 52 },
        content: scales_1,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 164, y: 46.5 },
        content: scales_2,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 1, y: 31.5 },
        content: "DRAWER",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 1, y: 27 },
        content: drawer_name,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 2.5 },
      },
      {
        type: "text",
        position: { x: 46, y: 31.5 },
        content: "DESIGNER",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 46, y: 27 },
        content: designer_name,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 2.5 },
      },
      {
        type: "text",
        position: { x: 1, y: 23 },
        content: "CHECKER",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 1, y: 18.5 },
        content: checker_name,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 2.5 },
      },
      {
        type: "text",
        position: { x: 46, y: 23 },
        content: "DATE",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 46, y: 18.5 },
        content: date,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 2.5 },
      },
      {
        type: "text",
        position: { x: 91, y: 14.5 },
        content: "PROJECT NUMBER",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 91, y: 10 },
        content: project_number,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 148, y: 14.5 },
        content: "DESIGN GROUP",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 148, y: 10 },
        content: design_group,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 91, y: 6 },
        content: "DWG. NO.",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 91, y: 1.5 },
        content: drawing_number,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 148, y: 6 },
        content: "PAGE",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 148, y: 1.5 },
        content: page,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
      {
        type: "text",
        position: { x: 171, y: 6 },
        content: "REVISION",
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 1.4 },
      },
      {
        type: "text",
        position: { x: 171, y: 1.5 },
        content: revision,
        hAlign: "right",
        vAlign: "top",
        styleOverride: { widthFactor: 0.8, textHeight: 3.5 },
      },
    ];
  },
});
